### ISSUE TITLE
Can't seem to get it working.

### ISSUE THREAD

**Issue by shendrick** [kristianmandrup/generator-stenciljs#2]
$ yo stenciljs:app
? Module Name stencil-generator-app
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'name' of undefined
    at askName.then.answer (/Users/qbnflaco/.nvm/versions/node/v8.2.1/lib/node_modules/generator-stenciljs/generators/app/index.js:54:23)
    at <anonymous>

**Comment by kristianmandrup** [comment]
Try previous version `0.0.1` I think. I'm aware there slipped in an error for this version. New much improved version coming out very soon, hopefully by tmrw.

See latest branch ;) Sorry to keep you waiting...

Cheers!

**Comment by kristianmandrup** [comment]
Note: I would think this is a very small slip that is easy to fix, most likely a name/reference error. Feel free to hunt it down by cloning the repo if you don't have patience... I'm over and out for tonight :P

**Comment by shendrick** [comment]
Great thanks! I'll give it a try.

**Comment by kristianmandrup** [comment]
If you are up for it, you are most welcome to help get the next release ready... 
The `page-component` branch. Using a test driven approach, as the project has grown quite a bit.
But I intend it pretty much as a "framework" for building generators now!
As all generators seem to have very similar requirements, no matter the target lib/framework

**Comment by kristianmandrup** [comment]
Fixed it now, version 0.0.3. Could really use some help to improve it ;)
